export default {
  SetANewPassword: 'Změna hesla',
  NewPassword: 'Nové heslo (aspoň 6 znaků)',
  Games: 'Seznam her',
  Login: 'Přihlásit se',
  Logout: 'Odhlásit se',
  ErrEmail: 'Toto pole musí obsahovat validní emailovou adresu',
  Submit: 'Potvrdit',
  ErrMessage: 'Zpráva nesmí být prázdná',
  Message: 'Zpráva',
  Help: 'Pomoc',
  ContactSupport: 'Kontaktovat podporu',
  ErrPassword: 'Heslo musí být dlouhé alespoň 6 znaků',
  Log: 'Přihlášení',
  Password: 'Heslo (aspoň 6 znaků)',
  ForgPassword: 'Zapomněl/a jsi heslo?',
  Pswdreneval: 'Obnova hesla',
  'We are sorry but your account was banned!': 'Je nám líto, ale byl ti zablokován účet!',
  'We are waiting for admins to verif your account.': 'Čekáme na to, až administrátoři ověří tvůj účet!',
  Refresh: 'Aktualizovat',
  Registration: 'Potřebuješ si vytvořit účet?',
  Name: 'Jméno',
  Registration_verb: 'Registrovat se',
  AddTag: 'Přidat tag',
  NameCs: 'Český název',
  NameEn: 'Anglický název',
  TagExistsEn: 'Tag s tímto anglickým názvem již existuje',
  TagExistsCs: 'Tag s tímto českým názvem již existuje',
  'User with given email does not exist': 'Uživatel s daným emailem neexistuje',
  'Error on our side': 'Chyba na naší straně, kontaktuje prosím podporu.',
  userAlreadyExists: 'Uživatel s daným emailem již existuje',
  WrongPassword: 'Špatné heslo!',
  TagsColumnCzechName: 'Český název',
  TagsColumnEnglishName: 'Anglický název',
  'Name of game': 'Název hry',
  Duration: 'Doba trvání',
  'Age groups': 'Věkové skupiny',
  'Number of players': 'Počet hráčů',
  Tags: 'Tagy',
  Author: 'Autor',
  'Last Change': 'Poslední změna',
  Kindergarden: 'Školka',
  School: 'Škola',
  Teenager: 'Teenager',
  Adult: 'Dospělý',
  K: 'Školka',
  S: 'Škola',
  T: 'Teenager',
  A: 'Dospělý',
  minutes: 'minut',
  'Duration of the game': 'Doba trvání hry',
  ErrEmptyName: 'Musí být vyplněn alespoň jeden název',
  ErrEmptyRule: 'Musí být vyplněno alespoň jedno pravidlo',
  ErrEmptyNameCs: 'Pole nesmí být prázdné',
  ErrEmptyNameEn: 'Pole nesmí být prázdné',
  'Name contains': 'Jméno obsahuje',
  "Author's name contains": 'Autorovo jméno obsahuje',
  'Filter tags': 'Filtr tagů',
  RemoveTag: 'Odstranit tag',
  'Do you really want to delete this tag ? Tag will be removed from all games!': 'Opravdu chceš odstranit tag? Tag bude odebrán ze všech her!',
  Cancel: 'Zrušit',
  Delete: 'Smazat',
  EditTag: 'Upravit tag',
  ErrMin: 'Pole "Minimální počet hráčů" musí obsahovat číslo',
  ErrMax: 'Pole "Maximální počet hráčů" musí obsahovat číslo',
  ErrDuration: 'Musí být vybrána jen jedna doba trvání',
  ErrAge: 'Musí být vybrána alespoň jedna kategorie věku',
  ErrTag: 'Musí být vybrán alespoň jeden tag',
  RulesCs: 'Pravidla v češtině',
  RulesEn: 'Pravidla v angličtině',
  NumberOfPlayersMin: 'Minimální počet hráčů',
  NumberOfPlayersMax: 'Maximální počet hráčů',
  CreateGame: 'Vytvořit hru'
};
