export default {
  Games: 'Seznam her',
  Login: 'Přihlásit se',
  ErrEmail: 'Toto pole musí obsahovat validní emailovou adresu',
  Submit: 'Potvrdit',
  ErrMessage: 'Zpráva nesmí být prázdná',
  Message: 'Zpráva',
  Help: 'Pomoc',
  ContactSupport: 'Kontaktovat podporu',
  ErrPassword: 'Heslo musí být dlouhé alespoň 6 znaků',
  Log: 'Přihlášení',
  Password: 'Heslo (aspoň 6 znaků)',
  ForgPassword: 'Zapomněl/a jsi heslo?',
  Pswdreneval: 'Obnova hesla',
  'We are sorry but your account was banned!': 'Je nám líto, ale byl ti zablokován účet!',
  'We are waiting for admins to verif your account.': 'Čekáme na to, až administrátoři ověří tvůj účet!',
  Refresh: 'Aktualizovat',
  Registration: 'Registrace',
  Name: 'Jméno',
  Registration_verb: 'Registrovat se',
  AddTag: 'Přidat tag',
  NameCs: 'Český název',
  NameEn: 'Anglický název',
  TagExistsEn: 'Tag s tímto anglickým názvem již existuje',
  TagExistsCs: 'Tag s tímto českým názvem již existuje',
  'User with given email does not exist': 'Uživatel s daným emailem neexistuje',
  'Error on our side': 'Chyba na naší straně, kontaktuje prosím podporu.',
  userAlreadyExists: 'Uživatel s daným emailem již existuje',
  WrongPassword: 'Špatné heslo!',
  TagsColumnCzechName: 'Český název',
  TagsColumnEnglishName: 'Anglický název',
  ErrEmptyNameCs: 'Pole "Český název" nesmí být prázdné',
  ErrEmptyNameEn: 'Pole "Anglický název" nesmí být prázdné',
  RemoveTag: 'Odstranit tag',
  'Do you really want to delete this tag ? Tag will be removed from all games!': 'Opravdu chceš odstranit tag ? Tag bude odebrán ze všech her!',
  Cancel: 'Zrušit',
  Delete: 'Smazat'
};
