export default {
  Games: 'Seznam her',
  Login: 'Přihlásit se',
  ErrEmail: 'Toto pole musí obsahovat validní emailovou adresu',
  Submit: 'Potvrdit',
  ErrMessage: 'Zpráva nesmí být prázdná',
  Message: 'Zpráva',
  Help: 'Pomoc',
  ContactSupport: 'Kontaktovat podporu',
  ErrPassword: 'Heslo musí být dlouhé alespoň 6 znaků',
  Log: 'Přihlášení',
  Password: 'Heslo (aspoň 6 znaků)',
  ForgPassword: 'Zapomněl/a jsi heslo?',
  Pswdreneval: 'Obnova hesla',
  'We are sorry but your account was banned!': 'Je nám líto, ale byl ti zablokován účet!',
  'We are waiting for admins to verif your account.': 'Čekáme na to, až administrátoři ověří tvůj účet!',
  Refresh: 'Aktualizovat',
  Registration: 'Registrace',
  Name: 'Jméno',
  Registration_verb: 'Registrovat se',
  TagsColumnCzechName: 'Český název',
  TagsColumnEnglishName: 'Anglický název',
  'Name of game': 'Název hry',
  Duration: 'Doba trvání',
  'Age groups': 'Věkové skupiny',
  'Number of players': 'Počet hráčů',
  Tags: 'Tagy',
  Author: 'Autor',
  'Last Change': 'Poslední změna',
  Kindergarden: 'Školka',
  School: 'Škola',
  Teenager: 'Teenager',
  Adult: 'Dospělý',
  K: 'Školka',
  S: 'Škola',
  T: 'Teenager',
  A: 'Dospělý',
  minutes: 'minut',
  'Duration of the game': 'Doba trvání hry'
};
