export default {
  Games: 'List of games',
  Login: 'Login',
  ErrEmail: 'This field must contain valid email address',
  Submit: 'Submit',
  ErrMessage: 'This field must not be empty',
  Message: 'Message',
  Help: 'Help',
  ContactSupport: 'Contact Support',
  ErrPassword: 'The password must be at least 6 characters long',
  Log: 'Login',
  Password: 'Password (at least 6 characters)',
  ForgPassword: 'Forgot password?',
  Pswdreneval: 'Password renewal',
  'We are sorry but your account was banned!': 'We are sorry, but your account has been blocked!',
  'We are waiting for admins to verif your account.': 'We are waiting for the administrators to verify your account.',
  Refresh: 'Refresh',
  Registration: 'Registration',
  Name: 'Name',
  Registration_verb: 'Registration',
  'User with given email does not exist': 'User with given email does not exist',
  'Error on our side': 'Error on our side, please contact support',
  userAlreadyExists: 'User with given mail already exists'
};
