export default {
  Games: 'List of games',
  Login: 'Login',
  ErrEmail: 'This field must contain valid email address',
  Submit: 'Submit',
  ErrMessage: 'The field Message must not be empty',
  Message: 'Message',
  Help: 'Help',
  ContactSupport: 'Contact Support',
  ErrPassword: 'The password must be at least 6 characters long',
  Log: 'Login',
  Password: 'Password (at least 6 characters)',
  ForgPassword: 'Forgot password?',
  Pswdreneval: 'Password renewal',
  'We are sorry but your account was banned!': 'We are sorry, but your account has been blocked!',
  'We are waiting for admins to verif your account.': 'We are waiting for the administrators to verify your account.',
  Refresh: 'Refresh',
  Registration: 'Registration',
  Name: 'Name',
  Registration_verb: 'Registration',
  AddTag: 'Add tag',
  NameCs: 'Czech name',
  NameEn: 'English name',
  TagExistsEn: 'Tag with this english name already exists',
  TagExistsCs: 'Tag with this czech name already exists',
  'User with given email does not exist': 'User with given email does not exist',
  'Error on our side': 'Error on our side, please contact support',
  userAlreadyExists: 'User with given mail already exists',
  WrongPassword: 'Wrong password!',
  TagsColumnCzechName: 'Czech name',
  TagsColumnEnglishName: 'English name',
  'Name of game': 'Name of game',
  Duration: 'Duration',
  'Age groups': 'Age groups',
  'Number of players': 'Number of players',
  Tags: 'Tags',
  Author: 'Author',
  'Last Change': 'Last change',
  Kindergarden: 'Kindergarden',
  School: 'School',
  Teenager: 'Teenager',
  Adult: 'Adult',
  K: 'Kindergarden',
  S: 'School',
  T: 'Teenager',
  A: 'Adult',
  minutes: 'minutes',
  'Duration of the game': 'Duration of the game',
  ErrEmptyName: 'At least one name must be filled',
  ErrEmptyRule: 'At least one rule must be filled',
  ErrEmptyNameCs: 'This field must not be empty',
  ErrEmptyNameEn: 'This field must not be empty',
  'Name contains': 'Name contains',
  "Author's name contains": "Author's name contains",
  'Filter tags': 'Filter tags',
  RemoveTag: 'Remove tag',
  'Do you really want to delete this tag ? Tag will be removed from all games!': 'Do you really want to delete this tag? Tag will be removed from all games!',
  Cancel: 'Cancel',
  Delete: 'Delete',
  EditTag: 'Edit tag',
  ErrMin: 'Field "Minimal number of players" must be number',
  ErrMax: 'Field "Maximal number of players" must be number',
  ErrDuration: 'Must be choosen exactly one duration',
  ErrAge: 'Must be choosen exactly one age group',
  ErrTag: 'Must be choosen exactly one tag',
  RulesCs: 'Rules in czech',
  RulesEn: 'Rules in english',
  NumberOfPlayersMin: 'Minimal number of players',
  NumberOfPlayersMax: 'Maximal number of players',
  CreateGame: 'Create game'
};
